name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ianwalter/puppeteer-container@v4.0.0
    - uses: actions/setup-node@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build-storybook
    - run: yarn test
