name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: true
      - run: pnpm run test
      - name: Tests
        run: |
          pnpm run storybook --ci &
          pnpm run creevey
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: report/
